"""Initial

Revision ID: 01244551978c
Revises: 
Create Date: 2024-04-24 21:43:45.111249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01244551978c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_chats')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('replyID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('srcUserID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('dstUserID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.drop_column('time')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.create_foreign_key('fk_community_userID', 'users', ['userID'], ['userID'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('requestID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('rewards',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('timelimit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key('fk_requests_userID', 'users', ['userID'], ['userID'])

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('itemID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('signs', schema=None) as batch_op:
        batch_op.alter_column('signID',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('userID',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=True)

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.alter_column('replyID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('threadID',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=True))
        batch_op.alter_column('todoID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('requestID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_todo_userID', 'users', ['userID'], ['userID'])
        batch_op.create_foreign_key('fk_todo_reqID', 'requests', ['requestID'], ['requestID'])
        batch_op.drop_column('Status')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transactionID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('itemID',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('userID',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('itemID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('userID',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('transactionID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.TEXT(), server_default=sa.text("'Not Done'"), nullable=False))
        batch_op.drop_constraint('fk_todo_reqID', type_='foreignkey')
        batch_op.drop_constraint('fk_todo_userID', type_='foreignkey')
        batch_op.alter_column('requestID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('userID',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('todoID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('status')

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('threadID',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('replyID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('signs', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('signID',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('itemID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_requests_userID', type_='foreignkey')
        batch_op.alter_column('userID',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('timelimit',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('rewards',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('requestID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_constraint('fk_community_userID', type_='foreignkey')
        batch_op.alter_column('userID',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.TEXT(), server_default=sa.text("'1970-01-01'"), nullable=False))
        batch_op.alter_column('dstUserID',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('srcUserID',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('replyID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    op.create_table('_alembic_tmp_chats',
    sa.Column('replyID', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('chatID', sa.TEXT(), nullable=False),
    sa.Column('srcUserID', sa.VARCHAR(length=120), nullable=True),
    sa.Column('dstUserID', sa.VARCHAR(length=120), nullable=True),
    sa.Column('content', sa.TEXT(), server_default=sa.text("'No Content'"), nullable=False),
    sa.ForeignKeyConstraint(['dstUserID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['srcUserID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('replyID')
    )
    # ### end Alembic commands ###
