"""empty message

Revision ID: 44795a558d23
Revises: 2bb5b4a47465
Create Date: 2024-05-12 16:37:22.239311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44795a558d23'
down_revision = '2bb5b4a47465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('faqID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('faqChat', schema=None) as batch_op:
        batch_op.alter_column('TransactionID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('userID',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=True,
               existing_server_default=sa.text("'None'"))
        batch_op.create_foreign_key('fk_faqchat_userID', 'users', ['userID'], ['userID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faqChat', schema=None) as batch_op:
        batch_op.drop_constraint('fk_faqchat_userID', type_='foreignkey')
        batch_op.alter_column('userID',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'None'"))
        batch_op.alter_column('TransactionID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('faqID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
