"""Add chatbot

Revision ID: 9cd4b2ac411c
Revises: 01244551978c
Create Date: 2024-05-12 16:10:15.283228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd4b2ac411c'
down_revision = '01244551978c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('faqID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('faqChat', schema=None) as batch_op:
        batch_op.alter_column('TransactionID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faqChat', schema=None) as batch_op:
        batch_op.alter_column('TransactionID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('faqID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
